apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: coursework-20200681-demo
    app.kubernetes.io/instance: coursework-20200681-demo-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: coursework-20200681-demo
  namespace: prod
spec:
  selector:
    app: coursework-20200681-demo
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
