apiVersion: v1
kind: ConfigMap
metadata:
  name: coinbase-exchange-db-script
data:
  mysql_coinbase_exchange_db.sql: |-
    CREATE USER 'cw_k8_user'@'%' IDENTIFIED WITH mysql_native_password BY 'Abcd1234';
    GRANT ALL PRIVILEGES ON *.* TO 'cw_k8_user'@'%';
    FLUSH PRIVILEGES;
    CREATE DATABASE IF NOT EXISTS coinbase_exchange_db_dev;
    USE coinbase_exchange_db_dev;
    CREATE TABLE money_transfer_history(
      history_id varchar(100),
        currency varchar(10),
        from_account varchar(200),
        to_account varchar(200),
        amount varchar(20)
    );
    CREATE TABLE activity_log(
      log_id varchar(100),
        action_type varchar(20),
        created_at varchar(50),
        data varchar(2000),
        path varchar(150)
    );
    CREATE DATABASE IF NOT EXISTS coinbase_exchange_db_test;
    USE coinbase_exchange_db_test;
    CREATE TABLE money_transfer_history(
      history_id varchar(100),
        currency varchar(10),
        from_account varchar(200),
        to_account varchar(200),
        amount varchar(20)
    );
    CREATE TABLE activity_log(
      log_id varchar(100),
        action_type varchar(20),
        created_at varchar(50),
        data varchar(2000),
        path varchar(150)
    );
    CREATE DATABASE IF NOT EXISTS coinbase_exchange_db_prod;
    USE coinbase_exchange_db_prod;
    CREATE TABLE money_transfer_history(
      history_id varchar(100),
        currency varchar(10),
        from_account varchar(200),
        to_account varchar(200),
        amount varchar(20)
    );
    CREATE TABLE activity_log(
      log_id varchar(100),
        action_type varchar(20),
        created_at varchar(50),
        data varchar(2000),
        path varchar(150)
    );

